# Generated by Django 4.0.4 on 2022-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETennis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scu', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True)),
                ('data_create', models.DateField(auto_now_add=True)),
                ('data_update', models.DateField(auto_now=True)),
                ('new_product', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('sport_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PadelNuestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scu', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True)),
                ('data_create', models.DateField(auto_now_add=True)),
                ('data_update', models.DateField(auto_now=True)),
                ('new_product', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('sport_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TennisPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scu', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True)),
                ('data_create', models.DateField(auto_now_add=True)),
                ('data_update', models.DateField(auto_now=True)),
                ('new_product', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('sport_type', models.CharField(max_length=255)),
            ],
        ),
    ]
