# Generated by Django 4.0.4 on 2022-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTennis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True)),
                ('data_create', models.DateField(auto_now_add=True)),
                ('data_update', models.DateField(auto_now=True)),
                ('is_sku', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('sport_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PadelNuestro',
        ),
        migrations.RemoveField(
            model_name='etennis',
            name='new_product',
        ),
        migrations.RemoveField(
            model_name='etennis',
            name='scu',
        ),
        migrations.RemoveField(
            model_name='tennispro',
            name='new_product',
        ),
        migrations.RemoveField(
            model_name='tennispro',
            name='scu',
        ),
        migrations.AddField(
            model_name='etennis',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etennis',
            name='is_sku',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etennis',
            name='sku',
            field=models.CharField(default='exit', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tennispro',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tennispro',
            name='is_sku',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tennispro',
            name='sku',
            field=models.CharField(default='exit', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
