# Generated by Django 4.0.4 on 2022-05-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0002_globaltennis_delete_padelnuestro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('best_price', models.FloatField(blank=True)),
                ('discount_e_tennis', models.FloatField(blank=True)),
                ('discount_global_tennis', models.FloatField(blank=True)),
                ('discount_tennis_pro', models.FloatField(blank=True)),
                ('price_e_tennis', models.FloatField(blank=True)),
                ('price_global_tennis', models.FloatField(blank=True)),
                ('price_tennis_pro', models.FloatField(blank=True)),
                ('delete_from_e_tennis', models.BooleanField(default=False)),
                ('delete_from_global_tennis', models.BooleanField(default=False)),
                ('delete_from_tennis_pro', models.BooleanField(default=False)),
                ('new_from_e_tennis', models.BooleanField(default=False)),
                ('new_from_global_tennis', models.BooleanField(default=False)),
                ('new_from_tennis_pro', models.BooleanField(default=False)),
                ('data_create', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['best_price', 'brand', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('best_avr_price', models.FloatField(blank=True)),
                ('avr_discount_e_tennis', models.FloatField(blank=True)),
                ('avr_discount_global_tennis', models.FloatField(blank=True)),
                ('avr_discount_tennis_pro', models.FloatField(blank=True)),
                ('avr_price_e_tennis', models.FloatField(blank=True)),
                ('min_price_e_tennis', models.FloatField(blank=True)),
                ('max_price_e_tennis', models.FloatField(blank=True)),
                ('change_price_percent_e_tennis', models.CharField(max_length=255)),
                ('avr_price_global_tennis', models.FloatField(blank=True)),
                ('min_price_global_tennis', models.FloatField(blank=True)),
                ('max_price_global_tennis', models.FloatField(blank=True)),
                ('change_price_percent_global_tennis', models.CharField(max_length=255)),
                ('avr_price_tennis_pro', models.FloatField(blank=True)),
                ('min_price_tennis_pro', models.FloatField(blank=True)),
                ('max_price_tennis_pro', models.FloatField(blank=True)),
                ('change_price_percent_tennis_pro', models.CharField(max_length=255)),
                ('delete_from_e_tennis', models.BooleanField(default=False)),
                ('delete_from_global_tennis', models.BooleanField(default=False)),
                ('delete_from_tennis_pro', models.BooleanField(default=False)),
                ('new_to_e_tennis', models.BooleanField(default=False)),
                ('new_to_global_tennis', models.BooleanField(default=False)),
                ('new_to_tennis_pro', models.BooleanField(default=False)),
                ('data_create', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['best_avr_price', 'brand', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('best_avr_price', models.FloatField(blank=True)),
                ('avr_discount_e_tennis', models.FloatField(blank=True)),
                ('avr_discount_global_tennis', models.FloatField(blank=True)),
                ('avr_discount_tennis_pro', models.FloatField(blank=True)),
                ('avr_price_e_tennis', models.FloatField(blank=True)),
                ('min_price_e_tennis', models.FloatField(blank=True)),
                ('max_price_e_tennis', models.FloatField(blank=True)),
                ('change_price_percent_e_tennis', models.CharField(max_length=255)),
                ('avr_price_global_tennis', models.FloatField(blank=True)),
                ('min_price_global_tennis', models.FloatField(blank=True)),
                ('max_price_global_tennis', models.FloatField(blank=True)),
                ('change_price_percent_global_tennis', models.CharField(max_length=255)),
                ('avr_price_tennis_pro', models.FloatField(blank=True)),
                ('min_price_tennis_pro', models.FloatField(blank=True)),
                ('max_price_tennis_pro', models.FloatField(blank=True)),
                ('change_price_percent_tennis_pro', models.CharField(max_length=255)),
                ('delete_from_e_tennis', models.BooleanField(default=False)),
                ('delete_from_global_tennis', models.BooleanField(default=False)),
                ('delete_from_tennis_pro', models.BooleanField(default=False)),
                ('new_from_e_tennis', models.BooleanField(default=False)),
                ('new_from_global_tennis', models.BooleanField(default=False)),
                ('new_from_tennis_pro', models.BooleanField(default=False)),
                ('data_create', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['best_avr_price', 'brand', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='etennis',
            options={'ordering': ['price', 'brand', 'title']},
        ),
        migrations.AlterModelOptions(
            name='globaltennis',
            options={'ordering': ['price', 'brand', 'title']},
        ),
        migrations.AlterModelOptions(
            name='tennispro',
            options={'ordering': ['price', 'brand', 'title']},
        ),
    ]
