# Generated by Django 4.0.4 on 2022-05-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0003_dailyanalytics_monthlyanalytics_weeklyanalytics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyanalytics',
            old_name='new_to_e_tennis',
            new_name='new_from_e_tennis',
        ),
        migrations.RenameField(
            model_name='monthlyanalytics',
            old_name='new_to_global_tennis',
            new_name='new_from_global_tennis',
        ),
        migrations.RenameField(
            model_name='monthlyanalytics',
            old_name='new_to_tennis_pro',
            new_name='new_from_tennis_pro',
        ),
    ]
